#' Titles
#'
#' @param p.vals s 
#'
#' @return s
#' @export
#'
#' 
EMLogLikelihood <- function(p.vals) {
  # Calculates log-likelihood of data fitting estimated distributions
  #
  # Args:
  #   p.vals: A matrix of p values generated by EMPvalues
  # Returns:
  #   The sum of log-likelihoods for the data
  # Convert to log likelihoods and sum
  p.vals <- log(rowSums(p.vals))
  log.likelihood <- sum(p.vals)
  return(log.likelihood)
}